# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created: Fri Sep 18 17:26:58 2009
#      by: PyQt4 UI code generator 4.5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 603)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.txtBookSentence = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtBookSentence.sizePolicy().hasHeightForWidth())
        self.txtBookSentence.setSizePolicy(sizePolicy)
        self.txtBookSentence.setMinimumSize(QtCore.QSize(250, 100))
        self.txtBookSentence.setMaximumSize(QtCore.QSize(16777215, 100))
        self.txtBookSentence.setObjectName("txtBookSentence")
        self.horizontalLayout_2.addWidget(self.txtBookSentence)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btnBook = QtGui.QPushButton(self.centralwidget)
        self.btnBook.setObjectName("btnBook")
        self.horizontalLayout_3.addWidget(self.btnBook)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.lblJournal = QtGui.QLabel(self.centralwidget)
        self.lblJournal.setStyleSheet("font: 14pt sans-serif bold;")
        self.lblJournal.setObjectName("lblJournal")
        self.horizontalLayout_4.addWidget(self.lblJournal)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.btnExportJournal = QtGui.QToolButton(self.centralwidget)
        self.btnExportJournal.setMinimumSize(QtCore.QSize(48, 0))
        self.btnExportJournal.setObjectName("btnExportJournal")
        self.horizontalLayout_4.addWidget(self.btnExportJournal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.listJournal = QtWebKit.QWebView(self.centralwidget)
        self.listJournal.setMinimumSize(QtCore.QSize(400, 0))
        self.listJournal.setUrl(QtCore.QUrl("about:blank"))
        self.listJournal.setObjectName("listJournal")
        self.horizontalLayout_5.addWidget(self.listJournal)
        spacerItem7 = QtGui.QSpacerItem(20, 348, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuBook = QtGui.QMenu(self.menubar)
        self.menuBook.setObjectName("menuBook")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockAccounts = QtGui.QDockWidget(MainWindow)
        self.dockAccounts.setFloating(False)
        self.dockAccounts.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockAccounts.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockAccounts.setObjectName("dockAccounts")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeAccounts = QtGui.QTreeWidget(self.dockWidgetContents)
        self.treeAccounts.setMinimumSize(QtCore.QSize(210, 0))
        self.treeAccounts.setAnimated(True)
        self.treeAccounts.setObjectName("treeAccounts")
        self.treeAccounts.headerItem().setText(0, "1")
        self.treeAccounts.header().setVisible(False)
        self.gridLayout_2.addWidget(self.treeAccounts, 0, 0, 1, 1)
        self.dockAccounts.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockAccounts)
        self.dockTAccount = QtGui.QDockWidget(MainWindow)
        self.dockTAccount.setFloating(False)
        self.dockTAccount.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockTAccount.setObjectName("dockTAccount")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnTAccViewRef = QtGui.QPushButton(self.dockWidgetContents_2)
        self.btnTAccViewRef.setObjectName("btnTAccViewRef")
        self.gridLayout_3.addWidget(self.btnTAccViewRef, 0, 0, 1, 1)
        self.btnExportAccounts = QtGui.QPushButton(self.dockWidgetContents_2)
        self.btnExportAccounts.setObjectName("btnExportAccounts")
        self.gridLayout_3.addWidget(self.btnExportAccounts, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.viewAccounts = QtWebKit.QWebView(self.dockWidgetContents_2)
        self.viewAccounts.setMinimumSize(QtCore.QSize(231, 0))
        self.viewAccounts.setUrl(QtCore.QUrl("about:blank"))
        self.viewAccounts.setObjectName("viewAccounts")
        self.gridLayout_4.addWidget(self.viewAccounts, 1, 0, 1, 1)
        self.dockTAccount.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockTAccount)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setCheckable(False)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLoad_account_file = QtGui.QAction(MainWindow)
        self.actionLoad_account_file.setEnabled(True)
        self.actionLoad_account_file.setObjectName("actionLoad_account_file")
        self.actionShow_accounts = QtGui.QAction(MainWindow)
        self.actionShow_accounts.setCheckable(True)
        self.actionShow_accounts.setChecked(True)
        self.actionShow_accounts.setObjectName("actionShow_accounts")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionFinish = QtGui.QAction(MainWindow)
        self.actionFinish.setObjectName("actionFinish")
        self.actionExport_Journal = QtGui.QAction(MainWindow)
        self.actionExport_Journal.setObjectName("actionExport_Journal")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionTAccount_View = QtGui.QAction(MainWindow)
        self.actionTAccount_View.setCheckable(True)
        self.actionTAccount_View.setVisible(True)
        self.actionTAccount_View.setObjectName("actionTAccount_View")
        self.actionExport_Accounts = QtGui.QAction(MainWindow)
        self.actionExport_Accounts.setObjectName("actionExport_Accounts")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_account_file)
        self.menuFile.addAction(self.actionTAccount_View)
        self.menuFile.addAction(self.actionShow_accounts)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuBook.addAction(self.actionExport_Journal)
        self.menuBook.addAction(self.actionExport_Accounts)
        self.menuBook.addSeparator()
        self.menuBook.addAction(self.actionFinish)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBook.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.label.setBuddy(self.txtBookSentence)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.dockAccounts, QtCore.SIGNAL("visibilityChanged(bool)"), self.actionShow_accounts.setChecked)
        QtCore.QObject.connect(self.dockTAccount, QtCore.SIGNAL("visibilityChanged(bool)"), self.actionTAccount_View.setChecked)
        QtCore.QObject.connect(self.actionTAccount_View, QtCore.SIGNAL("toggled(bool)"), self.dockTAccount.setVisible)
        QtCore.QObject.connect(self.actionShow_accounts, QtCore.SIGNAL("toggled(bool)"), self.dockAccounts.setVisible)
        QtCore.QObject.connect(self.actionExport_Journal, QtCore.SIGNAL("triggered()"), self.btnExportJournal.click)
        QtCore.QObject.connect(self.actionExport_Accounts, QtCore.SIGNAL("triggered()"), self.btnExportAccounts.click)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txtBookSentence, self.btnBook)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Buchhalter", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setStyleSheet(QtGui.QApplication.translate("MainWindow", "font: 14pt sans-serif bold;", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Buchungssatz", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBook.setText(QtGui.QApplication.translate("MainWindow", "Buchen", None, QtGui.QApplication.UnicodeUTF8))
        self.lblJournal.setText(QtGui.QApplication.translate("MainWindow", "Journal", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportJournal.setText(QtGui.QApplication.translate("MainWindow", "Export Journal", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBook.setTitle(QtGui.QApplication.translate("MainWindow", "&Book", None, QtGui.QApplication.UnicodeUTF8))
        self.dockAccounts.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Accounts", None, QtGui.QApplication.UnicodeUTF8))
        self.treeAccounts.setSortingEnabled(True)
        self.dockTAccount.setWindowTitle(QtGui.QApplication.translate("MainWindow", "TAccount View", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTAccViewRef.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportAccounts.setText(QtGui.QApplication.translate("MainWindow", "Export Accounts", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_account_file.setText(QtGui.QApplication.translate("MainWindow", "&Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_account_file.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_accounts.setText(QtGui.QApplication.translate("MainWindow", "&Show accounts", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_accounts.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+K", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFinish.setText(QtGui.QApplication.translate("MainWindow", "&Finish", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFinish.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Journal.setText(QtGui.QApplication.translate("MainWindow", "&Export Journal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Journal.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "&Load ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTAccount_View.setText(QtGui.QApplication.translate("MainWindow", "&TAccount View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTAccount_View.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Accounts.setText(QtGui.QApplication.translate("MainWindow", "Export Accounts", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
